Blackboard/Models/Announcement.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Blackboard.Models
{
    public class Announcement
    {
        public int Id { get; set; }
        [Required]
        [StringLength(30)]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [DisplayName ("Date and Time")]
        public string DateOfAnnouncement { get; set; }
        [DisplayName("Engagement")]
        public string NumberOfStudentsSeen { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ApplicationUser User { get; set; }
        
    }
}

Blackboard/Controllers/AnnouncementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blackboard.Models;
using Microsoft.AspNet.Identity;

namespace Blackboard.Controllers
{
    [RequireHttps]
    public class AnnouncementsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Announcements
        public ActionResult Index()
        {
            AddAllAnouncements();
            return View();
        }

        public void AddAllAnouncements()
        {
            ICollection<Announcement> announceList = db.Announcements.ToList();
            Relationship relationship = new Relationship();
            relationship.Announements = new List<Announcement>();

            foreach(var item in announceList)
            {
                relationship.Announements.Add(item);
            }

            db.Relationships = relationship;
            db.SaveChanges();
        }

        private IEnumerable<Announcement> GetMyAnnouncements()
        {
            String CurrentUserID = User.Identity.GetUserId();
            ApplicationUser CurrentUser = db.Users.FirstOrDefault(
            x => x.Id == CurrentUserID);
            return  db.Announcements.ToList().Where(x => x.User == CurrentUser);
        }

        public ActionResult BuildAnnouncementTable()
        {
            AddAllAnouncements();
            return PartialView("_AnnouncementTable", db.Relationships);
        }

        // GET: Announcements/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Announcement announcement = db.Announcements.Find(id);
            if (announcement == null)
            {
                return HttpNotFound();
            }
            return View(announcement);
        }

        // GET: Announcements/Create
        [Authorize(Roles = "Lecturer")]
        public ActionResult Create()
        {

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Lecturer")]
        public ActionResult Create([Bind(Include = "Id,Title,Description,DateOfAnnouncement")] Announcement announcement)
        {
            if (ModelState.IsValid)
            {
                string currentUserID = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(
                    x => x.Id == currentUserID);
                announcement.User = currentUser;
                announcement.Comments = new List<Comment>();
                announcement.DateOfAnnouncement = DateTime.UtcNow.ToString();
                db.Announcements.Add(announcement);
                AddAllAnouncements();
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(announcement);
        }

        // GET: Announcements/Edit/5
        [Authorize(Roles = "Lecturer")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Announcement announcement = db.Announcements.Find(id);
            if (announcement == null)
            {
                return HttpNotFound();
            }
            return View(announcement);
        }

        // POST: Announcements/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Lecturer")]
        public ActionResult Edit([Bind(Include = "Id,Title,Description,DateOfAnnouncement,NumberOfStudentsSeen")] Announcement announcement)
        {
            if (ModelState.IsValid)
            {
                
                db.Entry(announcement).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(announcement);
        }

        // GET: Announcements/Edit/5
        public ActionResult EditComment(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Announcements/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditComment([Bind(Include = "commentId,commentString,announceId")] Comment comment)
        {
            if (ModelState.IsValid)
            {

                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(comment);
        }

        // GET: Announcements/Delete/5


        // POST: Announcements/Delete/5
       

        // GET: Announcements/Delete/5
        public ActionResult EditDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Announcements/Delete/5
        [HttpPost, ActionName("EditDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult EditDeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AjaxCreate(Relationship comment, int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Announcement announcement = db.Announcements.Find(id);
            if (announcement == null)
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                announcement.Comments.Add(comment.CommentRelationship);
                db.Comments.Add(comment.CommentRelationship);
                db.SaveChanges();
                ModelState.Clear();
                return BuildAnnouncementTable();
            }


            return View(announcement);
        }

        // GET: Announcements/Delete/5
        [Authorize(Roles = "Lecturer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AjaxDeleteAnnouncement(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Announcement announcement = db.Announcements.Find(id);
            if (announcement == null)
            {
                return HttpNotFound();
            }

            LinkedList<Comment> cList = new LinkedList<Comment>(); 

            
            foreach (var comments in announcement.Comments)
            {
                cList.AddFirst(comments);
            }

            
            foreach (var comments in cList)
            {
                db.Comments.Remove(comments);
            }
            db.Announcements.Remove(announcement); 
            db.SaveChanges();

            return BuildAnnouncementTable();
        }
    }
}

Blackboard/Views/Announcements/Create.cshtml
@model Blackboard.Models.Announcement

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Announcement</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blackboard/Views/Announcements/Delete.cshtml
@model Blackboard.Models.Announcement

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Announcement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfAnnouncement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfAnnouncement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfStudentsSeen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfStudentsSeen)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Blackboard/Views/Announcements/Details.cshtml
@model Blackboard.Models.Announcement

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Announcement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfAnnouncement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfAnnouncement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfStudentsSeen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfStudentsSeen)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Blackboard/Views/Announcements/Edit.cshtml
@model Blackboard.Models.Announcement

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Announcement</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        @{
            DateTime MyValue = DateTime.Now;
            ViewBag.DateOfAnnouncement = MyValue.ToString("g");
        }

        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfAnnouncement, new { htmlAttributes = new { @class = "hidden", @Value = ViewBag.DateOfAnnouncement } })
                @Html.ValidationMessageFor(model => model.DateOfAnnouncement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfStudentsSeen, new { htmlAttributes = new { @class = "hidden" } })
                @Html.ValidationMessageFor(model => model.NumberOfStudentsSeen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blackboard/Views/Announcements/EditComment.cshtml
@model Blackboard.Models.Comment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Announcement</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CommentId)

        <div class="form-group">
            @Html.LabelFor(model => model.CommentString, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CommentString, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CommentString, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blackboard/Views/Announcements/EditDelete.cshtml
@model Blackboard.Models.Comment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete comment</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Announcement</h4>
        <p>
            @Html.DisplayNameFor(model => model.CommentString)
        </p>

        <p>
            @Html.DisplayFor(model => model.CommentString)
        </p>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Blackboard/Views/Announcements/Index.cshtml
@model Blackboard.Models.Announcement
@{
    ViewBag.Title = "Index";
}
<link href="~/Content/Home.css" rel="stylesheet" />
<div id="create">

    <h2 id="titleMain">Announcements</h2>

@if (User.IsInRole("Lecturer"))
{
    <p>
            @Html.ActionLink("Create announcement", "Create")

        
       
    </p>
}
</div>



<div id="tableDiv"></div>

@section Scripts
{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Custom_Scripts/BuildTable.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
}

Blackboard/Views/Announcements/_AnnouncementTable.cshtml
@model Blackboard.Models.Relationship



@foreach (var item in Model.Announements.Reverse())
{
    <div id="announceDetail">

        <b>
            @Html.DisplayNameFor(model => item.Title):
        </b>
        @Html.DisplayFor(modelItem => item.Title)


        <div id="Description">
            <p>
                <b>
                    @Html.DisplayNameFor(model => item.Description):
                </b>
                @Html.DisplayFor(modelItem => item.Description)
            </p>
        </div>
        <p>
            <b>
                @Html.DisplayNameFor(model => item.DateOfAnnouncement):
            </b>
            @Html.DisplayFor(modelItem => item.DateOfAnnouncement)
        </p>
        @if (User.IsInRole("Lecturer"))
        {
            <p>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            </p>
        }

        @using (Ajax.BeginForm("AjaxDeleteAnnouncement", "Announcements", new { id = item.Id }, new AjaxOptions
        {
            InsertionMode = InsertionMode.Replace,
            HttpMethod = "POST",
            UpdateTargetId = "tableDiv"
        }))
        {
            if (User.IsInRole("Lecturer"))
            {
                @Html.AntiForgeryToken()
                <input type="submit" value="Delete" class="btn btn-default" />
            }

        }


    </div>
        <div id="commentPadding">
            <b>
                Comment Section
            </b>
        </div>
    foreach (var itemComment in item.Comments.Reverse())
    {
        <div id="commentSection">
            <p>
                @Html.DisplayFor(modelItem => itemComment.CommentString)
            </p>

            <p>
                @if (User.IsInRole("Lecturer"))
                    {
                    @Html.ActionLink("Delete", "EditDelete", new { id = itemComment.CommentId })
                }
            </p>
        </div>
    }

    using (Ajax.BeginForm("AjaxCreate", "Announcements", new { id = item.Id }, new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        UpdateTargetId = "tableDiv"
    }))

    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CommentRelationship.CommentString, htmlAttributes: new { @class = "control-label col-md-2" })
            <div id="">
                @Html.EditorFor(model => model.CommentRelationship.CommentString, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CommentRelationship.CommentString, "", new { @class = "text-danger" })
            </div>
        </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
    }

}